### ISSUE TITLE
override_old_package not working

### ISSUE THREAD

**Issue by subzero911** [chandrabezzo/package_rename#2]
My config:

```yaml
package_rename_config:
  android:
    app_name: Тудуду
    package_name: online.tododo.app
    override_old_package: online.tododo.app
    lang: kotlin

  ios:
    app_name: Тудуду
    bundle_name: Тудуду
    override_old_package: online.tododo.app
    package_name: online.tododo.app;
```

Result - still the old path to MainActivity:

<img width="239" alt="image" src="https://github.com/chandrabezzo/package_rename/assets/12999702/a247786c-098c-49a8-815b-a114295993c2">

Also, still an old package in MainActivity.kt:
<img width="568" alt="image" src="https://github.com/chandrabezzo/package_rename/assets/12999702/0c7da002-d3b9-404a-acd1-d5b87c3d8a1a">

**Comment by chandrabezzo** [comment]
Hi @subzero911 thanks for the report, have you check the full example [here](https://github.com/chandrabezzo/package_rename/blob/main/example/example.md#flavour-configuration)?

**Comment by subzero911** [comment]
> Hi @subzero911 thanks for the report, have you check the full example [here](https://github.com/chandrabezzo/package_rename/blob/main/example/example.md#flavour-configuration)?

Yes, but I'm targeting only Android and iOS, so I omitted other platform configs.

**Comment by chandrabezzo** [comment]
Hi @subzero911 have you try with this value
```yaml
package_rename_config:
  android:
    app_name: Тудуду
    package_name: online.tododo.app
    override_old_package: com.example.goldy
    lang: kotlin

  ios:
    app_name: Тудуду
    bundle_name: tododo
    override_old_package: com.example.goldy
    package_name: online.tododo.app
```
